#!/bin/bash

export GIT_SSH="/${VCS_MIRROR_CODE_ROOT}/fakessh"

PROJECT="$1"

if [ "x$PROJECT" == "x" ]; then
    echo "I need a project name as an argument."
    exit 1
fi

#####

ROOT="/${VCS_MIRROR_REPO_ROOT}/$PROJECT.git"
echo "Sync'ing $ROOT."

cd $ROOT

# Alright. Let's sync up.

git remote update --prune
git fetch origin
git fetch origin --tags

# Alright. Let's push out.

git push push --mirror
